### ISSUE TITLE
Notes from @ctb

### ISSUE THREAD

**Issue by arokem** [richford/cloudknot#107]
https://hackmd.io/CYFgpgTAZsEIYFoBGA2A7IkAGFBWZWAnIQilCllBElmFpUA=

I think that there are two separate things here: 

- [ ] AWS bucket creation. Looks like there is a fix suggested in the notes, and configuration should automatically take into account these things.
- [ ] More detailed installation instructions. In particular, Docker is a dependency!

**Comment by richford** [comment]
Thanks @ctb for taking cloudknot for a spin and for writing up your impressions and suggestions. I'm sorry you had to spend so much time getting it to work. That's super frustrating and your willingness to push through that helps us make cloudknot better.

My latest commit to the `unified-ecr-repo` branch includes a cloudknot CLI. Right now it has only one subcommand, `configure` which runs `aws configure` and then also creates some resources on Amazon ECR. That `aws configure` step should create the `~/.aws/config` and `~/.aws/credentials` files, complete with the region option that you were missing.

Along with some better documentation about having to install and run Docker, I hope that'll resolve the issues you experienced.

**Comment by arokem** [comment]
I think that it, in addition to documentation, it would be worth having a check in the `__init__` to see whether the user has Docker installed, and then raise an informative error if they don't: "I see that you don't have Docker installed. Please go to https://docs.docker.com/engine/installation/ to install it"

**Comment by ctb** [comment]
great, thanks folks!

I am at the airport so I don't want to experiment more, but I'm curious
about how possible it will be to have some "prepared" docker containers
somewhere. It seems like a potential problem to have to upload a new docker
container each time, e.g. when traveling or when preloading docker containers
with cool stuf or for demos or ...

best,
--titus

**Comment by richford** [comment]
@ctb, you're reading my mind. The unified-ecr-repo branch pushes the python base images to ECR. This cuts down on the pull and push times significantly since Docker can reuse the layers for the python base images. Beyond the base image, all of the cloudknot docker images can share their layers with one another since they reside in the same AWS ECR repository. So subsequent push and pull commands should be pretty quick.

Do you mean "prepared" docker containers with more than just the base images?

**Comment by ctb** [comment]
both options are good, but I think you already have the latter option available
with the DockerRepo API, right? I haven't tried it tho :)

the lightweight option you just described (reusing the layers) is excellent!

**Comment by richford** [comment]
v0.2.1 should fix these.
