### ISSUE TITLE
`cloudknot configure` fails

### ISSUE THREAD

**Issue by dtenenba** [richford/cloudknot#111]
It looks like the cloudknot/__init__.py (which expects everything to be configured) is run before the configure subcommand can be run, creating a chicken and egg problem where I cannot configure cloudknot.

Running `cloudknot configure` gives me an error telling me to run `cloudknot configure`.

python 3.6.3
cloudknot==0.3.dev0 (619be146885080fd748c98440ad6b17637c2bc7e)
macOS 10.12.6

I created a virtualenv with virtualenvwrapper:

```
$ mkvirtualenv -p $(which python3.6) cloudknot_env
...
$ pip install cloudknot
...
$ rm -f ~/.aws/cloudknot # just to prove it's not there
$ cloudknot configure
Traceback (most recent call last):
  File "/Users/dtenenba/envs/cloudknot_env/bin/cloudknot", line 11, in <module>
    load_entry_point('cloudknot==0.3.dev0', 'console_scripts', 'cloudknot')()
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/cloudknot-0.3.dev0-py3.6.egg/cloudknot/__init__.py", line 50, in <module>
    "It looks like you haven't run `cloudknot configure` to set up "
ImportError: It looks like you haven't run `cloudknot configure` to set up your cloudknot environment. Or perhaps you did that but you have since deleted your cloudknot configuration file. Please run `cloudknot configure` before using cloudknot.
```

**Comment by richford** [comment]
@dtenenba, Thanks for catching that. I just submitted #112 to resolve this. I was being overly specific when checking the `load_entry_point` on import so it was passing with the versions of cloudknot on pypi but not on the dev versions on github. Good catch! Once the travis-ci builds pass, I'll merge.

**Comment by dtenenba** [comment]
Thanks, not sure what happened to the Travis build, maybe a timeout? Can it be restarted?

**Comment by dtenenba** [comment]
I applied the commit in #112 to my code and installed it, now I get the following problem. 
It seems that cloudknot is not honoring my AWS_PROFILE and AWS_DEFAULT_REGION environment variables. I've set them to a non-default profile. The account number for that profile starts with a 3 (not a 5) and I've set default region to us-west-2. `aws sts get-caller-identity` does honor AWS_PROFILE and returns the correct information. 

I worked around this by editing `~/.aws/cloudknot` to change profile and region and re-ran `cloudknot configure`, this time it asked me which profile I wanted to use (it did not ask the first time), and suggested the one I'd changed it to. Now it appears to be pulling/pushing as expected.

I'd like `cloudknot configure` to ask which profile I want to use the first time.

Thanks!


```
$ cloudknot configure

`cloudknot configure` is passing control over to `aws configure`. If you have already configured AWS CLI just press <ENTER> at the prompts to accept the pre-existing values. If you have not yet configured AWS CLI, please follow the prompts to start using cloudknot.

AWS Access Key ID [****************WB7A]:
AWS Secret Access Key [****************LHiR]:
Default region name [us-west-2]:
Default output format [None]:

`aws configure` complete. Resuming configuration with `cloudknot configure`

Traceback (most recent call last):
  File "/Users/dtenenba/envs/cloudknot_env/bin/cloudknot", line 11, in <module>
    load_entry_point('cloudknot==0.3.dev0', 'console_scripts', 'cloudknot')()
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/cloudknot-0.3.dev0-py3.6.egg/cloudknot/cli.py", line 38, in main
    command.run()
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/cloudknot-0.3.dev0-py3.6.egg/cloudknot/commands/configure.py", line 78, in run
    ('ecr_repo', "Default AWS ECR repository name", get_ecr_repo()),
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/cloudknot-0.3.dev0-py3.6.egg/cloudknot/aws/base_classes.py", line 66, in get_ecr_repo
    set_ecr_repo(repo)
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/cloudknot-0.3.dev0-py3.6.egg/cloudknot/aws/base_classes.py", line 98, in set_ecr_repo
    repositoryNames=[repo]
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/botocore-1.8.11-py3.6.egg/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/dtenenba/envs/cloudknot_env/lib/python3.6/site-packages/botocore-1.8.11-py3.6.egg/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the DescribeRepositories operation: User: arn:aws:iam::555219204010:user/dtenenba is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:555219204010:repository/cloudknot
```

**Comment by richford** [comment]
Merged #112, which auto-closed this issue, but I'm reopening to address the second point you brought up.

**Comment by richford** [comment]
@dtenenba For reference, one of the travis pr builds failed because of a VPC resource limitation. The AWS account that cloudknot uses for its travis builds had too many VPCs. I only bring this up because I noticed that you are at Fred Hutch and might have a lot of users on one organizational account. So that may be relevant to you as well. There's more info on this in the [cloudknot documentation here](https://richford.github.io/cloudknot/getting_started.html#aws-resource-limitations).

Side note: this won't be as much of an issue if your org doesn't have any EC2 classic resources since then cloudknot will just use the default VPC. Unfortunately, cloudknot's own organizational account has some legacy EC2 classic resources so we have to contend with that while unit testing.

**Comment by richford** [comment]
@dtenenba, for the second issue you raised above, you're right that cloudknot doesn't reference the `AWS_PROFILE` environment variable. I've opened up a new issue for that (see #114).

But the larger issue is that the configure script was trying to retrieve the default_ecr_repo name before the profile was set. Thanks for pointing that out. PR #115 addresses that. I've tested it on my end. Once I merge it, would you mind testing on your end as well?

I hope that resolves the issue. In either case, thanks so much for submitting an issue. It really helps to make cloudknot better and more useful for researchers. Let me know how it works out.

**Comment by dtenenba** [comment]
Thanks for letting me know about that. Now that these issues are fixed I have tried CloudKnot and it's nice. As you surmise I am at Fred Hutch and I'm working on rolling out AWS Batch internally.

I have a number of questions for you -- this may not be the best place to discuss them-- you can email me at <my github username>@fredhutch.org.

Basically my questions have to do with adapting cloudknot to run in an AWS account that is shared by many IAM users, where end users do not have full Batch permissions. Specifically, end users cannot create compute environments or queues. They also cannot create S3 buckets, but every user has a bucket (that of their lab or administrative division) they can read/write to/from. 
Is it possible to specify a pre-existing compute environment and queue? This would also avoid the problem of running out of compute environments and queues (there are by default pretty low limits on the number of each of these that one account can have). 

Also we will need to be able to specify a job role in order to be able to use S3. Can that be supported somehow? 

Also wondering if you have thoughts about using Batch's new [array jobs](https://docs.aws.amazon.com/batch/latest/userguide/array_jobs.html) to power cloudknot. It would require some code changes.

Finally, we have a strong demand for something just like cloudknot but for R instead of python. I'm wondering how much work it would take to tweak cloudknot to make that work. 

I'm interested to hear if any of these features are supported. If not, are you open to PRs to implement them?

Thank you!
Dan

**Comment by dtenenba** [comment]
One more question - what if my cloudknot function requires a third-party package (that's not already installed on the docker image)? Is that supported? Pardon me if this is already documented, I have not yet finished reading the documentation.

**Comment by richford** [comment]
@dtenenba PRs are always welcome. I'm definitely open to them. I tried to split the remaining questions into new issues. Please feel free to correct me on those issues if I mischaracterize your questions.

Assuming I covered the above in the new issues. I'm going to close this one.
