### ISSUE TITLE
S3 access via job role.

### ISSUE THREAD

**Issue by richford** [richford/cloudknot#120]
Continuing from #111. From @dtenenba:

> Also we will need to be able to specify a job role in order to be able to use S3. Can that be supported somehow?

**Comment by richford** [comment]
`Knot` has an input argument called `pars_policies` that accepts a tuple of names of AWS policies to attach to each role so that the batch service roles, instance roles, task roles, etc. can access certain resources. Is this what you mean?

**Comment by dtenenba** [comment]
No, I'm just talking about how to attach a task role to a Batch job. 
BTW, end users here will have no IAM permissions either....

**Comment by richford** [comment]
Yep, `pars_policies` will attach an IAM policy to the user's batch jobs. See [this example](https://github.com/richford/cloudknot/blob/master/examples/03_write_to_s3_bucket.ipynb) for an example with "AmazonS3FullAccess."

**Comment by richford** [comment]
@dtenenba, I'm assuming this resolved the issue. If not, please feel free to reopen.
