### ISSUE TITLE
Allow user to supply SSE key for S3 bucket put and get operations

### ISSUE THREAD

**Issue by richford** [richford/cloudknot#122]
Continuing from #116. From @dtenenba:

> Also (I'm anticipating the next problem) all buckets in our account have a bucket policy attached that requires files be uploaded with server side encryption set to AES256. Is there a way to specify that be used for all cloudknot uploads?

We can allow the user to supply the key for local operations. But we'll also need some way to supply it to the running instances. Perhaps using [Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) would solve this on the instance side.

**Comment by dtenenba** [comment]
Thanks. Just to be clear, this is not an issue of supplying secrets. It just means that all uploads to the bucket need to specify ServerSideEncryption with AES256 (so in the cli it would be `aws s3 cp --sse AES256 file s3://bucket/file` and in boto3 it's usually a matter of adding `ServerSideEncryption='AES256'` to whatever method you are using to do the uploading (`put_object()`, `upload_file()`, etc. So using Systems Manager may be overkill. Probably just having an environment variable like `SERVER_SIDE_ENCRYPTION` with value `AES256`, that cloudknot would honor if it is set, would do the trick.

This setting is not required for downloads.

**Comment by richford** [comment]
@dtenenba, I believe #123 addresses this. Could you give it a whirl?

**Comment by richford** [comment]
Closing assuming the #123 fixes this. Feel free to reopen if it doesn't.
