### ISSUE TITLE
Cloudknot equivalent of `docker system prune`

### ISSUE THREAD

**Issue by arokem** [richford/cloudknot#144]
A function that finds all of your dangling provisioned resources and clobbers all of them.

**Comment by richford** [comment]
Likely redundant to #8 and #136. But I'll take it a sign that this issue is high priority since there are multiple versions of it. Closing as redundant but feel free to reopen if you feel it's distinct.

**Comment by arokem** [comment]
Yeah - if I understand correctly, `config.prune` is what we need. I just
noticed that we have multiple resources allocated through our AWS
allocation, and clobbering them one by one is a PITN.
