### ISSUE TITLE
AWS permissions error. 

### ISSUE THREAD

**Issue by ccurtis7** [richford/cloudknot#152]
I'm trying to train new users on Cloudknot, but I'm getting an error when trying to run

`cloudknot configure`

I get the following error:

`An error occurred (AccessDeniedException) when calling the DescribeRepositories operation: User: arn:aws:iam::153124814129:user/hpontes is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:153124814129:repository/cloudknot`

I found some idea of where the problem is in the [AWS documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html): "If you are performing actions against an Amazon ECR repository, verify that the user has been granted permissions to access that repository."

I don't think it has to do with additional policies, as I gave all users in the lab AWSBatchFullAccess. Any ideas how to fix?

**Comment by arokem** [comment]
Just a heads up that if this resource is stored on the uwescience AWS allocation, this might be a temporary thing, because that allocation is undergoing some changes at the moment. So, this might be a temporary glitch.

**Comment by ccurtis7** [comment]
I just figured part of it out. Cloudknot must create a repository under the Elastic Container Service. I found it in our resources. I am able to modify the policies. with a policy builder, but the darn thing says I also need to:

After generating the policy document, be sure to add the 'ecr:GetAuthorizationToken' action to the policy attached to the users and roles you selected below.

![image](https://user-images.githubusercontent.com/16652719/42911061-5f9b6dca-8a9e-11e8-93c9-4b3085f143d0.png)

**Comment by ccurtis7** [comment]
Figured out the last part. I had to add the policy "AmazonEC2ContainerRegistryPowerUser" to the permissions of each user. Then cloudknot configure worked on their machines.

Here's the [link](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html).
