### ISSUE TITLE
Allow users  to set the Python version in the docker container

### ISSUE THREAD

**Issue by arokem** [richford/cloudknot#189]
Right now, the Python version is inherited from the calling environment. 

It's also using the major Python version,  which can lead to some confusion when a  new version of Python is released (Fixed through this hack,  for example: https://github.com/richford/cloudknot/pull/188/commits/5ef2e31362bcfe6a960fff57ab40d8c13baf6353).

Might it make sense to add a "python_version" key-word argument to the `Knot.__init__` method?

**Comment by arokem** [comment]
I guess this can also be done by selecting the `base_image`  in a separately definted DockerImage object?

**Comment by richford** [comment]
Yep. And `Knot` also accepts a `base_image` parameter. I think that might resolve the issue. Okay to close this?

**Comment by arokem** [comment]
Yes. Closing!
