### ISSUE TITLE
Unable to create new knot  with spot instances

### ISSUE THREAD

**Issue by ishanbhagawati** [richford/cloudknot#190]
Hi When we try to create a new knot it fails with the following error
`WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state`

upon looking into the root I found that **_Policy arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole does not exist or is not attachable_**

AWS has deprecated the AmazonEC2SpotFleetRole and thus this error

**Comment by ishanbhagawati** [comment]
Upon discussing this with AWS I found out that **_The policy "arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole" is the replacement policy and going forward you should use this policy instead of "AmazonEC2SpotFleetRole"_**

**Comment by arokem** [comment]
Thanks for reporting and  hunting this down. I believe this should be resolved once we merge #188, but we still need to sort out the CI on that one.

**Comment by ccurtis7** [comment]
Thanks for pointing this @ishanbhagawati, we are having the same errors pop up in our regular workflows. @arokem any idea of the timeline on that merge?

**Comment by arokem** [comment]
Sorry about that. Looks like @richford and I are going to meet on Monday to fix our CI and I think that we should be able to merge that PR and cut a new release then.

**Comment by arokem** [comment]
Hey @ccurtis7 and @ishanbhagawati : this should now be resolved in the master branch. Does that suffice for you for now, or do you need us to cut a new release in a hurry. I think that we'd rather resolve a couple of issues with the CI before we do that, but we can also start with that, and then release again after we've figured out those other issues.

**Comment by ishanbhagawati** [comment]
@arokem It should do for moment for me. Thank you for making the changes :)

**Comment by arokem** [comment]
I believe this was fixed in #192
