### ISSUE TITLE
'list' object has no attribute 'decode'

### ISSUE THREAD

**Issue by 36000** [richford/cloudknot#195]
After runnning this command:

rb_knot = ck.Knot(name='bundle_hcp-64gb-191126-01',
                  func=bundle_hcp,
                  base_image='python:3.7',
                  image_github_installs="https://github.com/36000/pyAFQ.git",
                  pars_policies=('AmazonS3FullAccess',),
                  resource_type="SPOT",
                  bid_percentage=100,
                  memory=64000)

I get the following output:

![image](https://user-images.githubusercontent.com/9562159/69652587-c057c280-1026-11ea-86e6-697b591a8a7c.png)

**Comment by richford** [comment]
The cryptic error message is resolved in #196 and @36000 revealed through personal correspondence that the underlying issue no longer occurs. Closing out.
