### ISSUE TITLE
Unable to create knot

### ISSUE THREAD

**Issue by MarekGn** [richford/cloudknot#197]
When I want to run the example "random_matrix_vector_multiply" code I receive:
`botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state`

AWS CloudFormation events log says:
`SpotFleetRole | CREATE_FAILED | Policy arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 0ebf041c-693e-4b9f-bfc3-d0c87bff9447)`

What could be the reason?

**Comment by arokem** [comment]
Hi @MarekGn : thanks for reporting! How did you install the software? We recently updated the software with some fixes, but we have not made a release to pypi yet.

**Comment by MarekGn** [comment]
Ahh, I see. I changed the way of installation from pypi to git and now everything is ok. Thank You!
